[package]
name = "wahgex"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/declanvk/wahgex"
readme = "README.md"
keywords = []
categories = []
edition = "2021"
rust-version = "1.65"

[dependencies]
